[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
board_build.f_cpu = 240000000L

monitor_speed = 115200

; --- O PULO DO GATO (Octal PSRAM + 16MB Flash) ---
; Define o modo de memória híbrido: Flash em QIO e PSRAM em OPI
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

; Força o tamanho da Flash para 16MB (senão ele acha que é 4MB)
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

; Flags essenciais para ativar a PSRAM no compilador
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue ; (Opcional no S3, mas mal não faz)

; --- SISTEMA DE ARQUIVOS ---
board_build.filesystem = littlefs
; ATENÇÃO: O nome do arquivo aqui tem que bater com o que você criou na pasta
board_build.partitions = partitions_custom.csv

lib_deps =
    earlephilhower/ESP8266Audio @ ^1.9.7