# CMake generated Testfile for 
# Source directory: C:/Users/devx/Documents/PlatformIO/Projects/hydra
# Build directory: C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[core_smoke]=] "C:/emsdk/node/22.16.0_64bit/bin/node.exe" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web/hydra_core_smoke.js")
set_tests_properties([=[core_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;28;add_test;C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;0;")
add_test([=[core_regression]=] "C:/emsdk/node/22.16.0_64bit/bin/node.exe" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web/hydra_core_regression.js")
set_tests_properties([=[core_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;32;add_test;C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;0;")
add_test([=[core_abi_symbols]=] "C:/Users/devx/AppData/Local/Python/pythoncore-3.14-64/python.exe" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/abi_symbols_check.py" "--nm" "C:/emsdk/upstream/emscripten/emnm.bat" "--library" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web/libhydra_dsp_core.a")
set_tests_properties([=[core_abi_symbols]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;34;add_test;C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;0;")
add_test([=[test_golden_delay_modes]=] "C:/Users/devx/AppData/Local/Python/pythoncore-3.14-64/python.exe" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/golden_test.py" "--runner" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web/hydra_golden_regression_native.js" "--scenario" "delay_modes" "--fixtures-root" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/fixtures" "--compare-script" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/golden_compare.py")
set_tests_properties([=[test_golden_delay_modes]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;46;add_test;C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;0;")
add_test([=[test_golden_reset_state]=] "C:/Users/devx/AppData/Local/Python/pythoncore-3.14-64/python.exe" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/golden_test.py" "--runner" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web/hydra_golden_regression_native.js" "--scenario" "reset_state" "--fixtures-root" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/fixtures" "--compare-script" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/golden_compare.py")
set_tests_properties([=[test_golden_reset_state]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;54;add_test;C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;0;")
add_test([=[test_golden_param_automation]=] "C:/Users/devx/AppData/Local/Python/pythoncore-3.14-64/python.exe" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/golden_test.py" "--runner" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web/hydra_golden_regression_native.js" "--scenario" "param_automation" "--fixtures-root" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/fixtures" "--compare-script" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/golden_compare.py")
set_tests_properties([=[test_golden_param_automation]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;62;add_test;C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;0;")
add_test([=[native_vs_wasm_equivalence]=] "C:/Users/devx/AppData/Local/Python/pythoncore-3.14-64/python.exe" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/compare_native_wasm.py" "--native" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web/hydra_render_trace_native.js" "--wasm-js" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web/wasm-tests/hydra_render_trace.js" "--max-abs-threshold" "1e-5" "--rmse-threshold" "1e-6")
set_tests_properties([=[native_vs_wasm_equivalence]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;138;add_test;C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;0;")
add_test([=[native_wasm_ab_review_package]=] "C:/Users/devx/AppData/Local/Python/pythoncore-3.14-64/python.exe" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/build_ab_review_package.py" "--native" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web/hydra_render_trace_native.js" "--wasm-js" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web/wasm-tests/hydra_render_trace.js" "--null-test-script" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/null_test_wav.py" "--output-dir" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web/ab_review" "--max-abs-threshold" "1e-5" "--rmse-threshold" "1e-6")
set_tests_properties([=[native_wasm_ab_review_package]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;147;add_test;C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;0;")
add_test([=[test_golden_delay_modes_wasm]=] "C:/Users/devx/AppData/Local/Python/pythoncore-3.14-64/python.exe" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/golden_test.py" "--runner" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web/wasm-tests/hydra_golden_regression.js" "--scenario" "delay_modes" "--fixtures-root" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/fixtures" "--compare-script" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/golden_compare.py" "--wasm")
set_tests_properties([=[test_golden_delay_modes_wasm]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;175;add_test;C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;0;")
add_test([=[test_golden_reset_state_wasm]=] "C:/Users/devx/AppData/Local/Python/pythoncore-3.14-64/python.exe" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/golden_test.py" "--runner" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web/wasm-tests/hydra_golden_regression.js" "--scenario" "reset_state" "--fixtures-root" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/fixtures" "--compare-script" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/golden_compare.py" "--wasm")
set_tests_properties([=[test_golden_reset_state_wasm]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;184;add_test;C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;0;")
add_test([=[test_golden_param_automation_wasm]=] "C:/Users/devx/AppData/Local/Python/pythoncore-3.14-64/python.exe" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/golden_test.py" "--runner" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/build-web/wasm-tests/hydra_golden_regression.js" "--scenario" "param_automation" "--fixtures-root" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/fixtures" "--compare-script" "C:/Users/devx/Documents/PlatformIO/Projects/hydra/tests/core/golden_compare.py" "--wasm")
set_tests_properties([=[test_golden_param_automation_wasm]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;193;add_test;C:/Users/devx/Documents/PlatformIO/Projects/hydra/CMakeLists.txt;0;")
